# Generated by Django 5.0.7 on 2024-08-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'd'), ('Published', 'p')], max_length=9),
        ),
    ]
